name: Check Formatting
on:
  - push
  - pull_request

jobs:
  check:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --no-cache-dir -e '.[dev]'
          pre-commit install
      - name: Check formatting
        run: pre-commit run --all-files
